language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - make install

# command to run tests
script:
  - make test

before_deploy: sed -i "s/version=\".*\"/version=\"$TRAVIS_TAG\"/g" setup.py

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
